plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.wangyao.webrtcdemo'
    compileSdk 34

    defaultConfig {
        applicationId "com.wangyao.webrtcdemo"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.22.1'
        }
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    
    // WebRTC - 使用社区维护版本
    implementation 'io.github.webrtc-sdk:android:125.6422.02'
    
    // WebSocket
    implementation 'org.java-websocket:Java-WebSocket:1.5.3'
    
    // JSON
    implementation 'com.alibaba:fastjson:1.1.72.android'
}